[[Xorg_libXcomposite]]
arch = "aarch64"
git-tree-sha1 = "21ffca0660b56f6d55eea8e9cb8a96a3b3369938"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "39a7d74864605e83187c5d1fb6c31b427d9fd07c2cdde948e299325fa26dcd9b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.aarch64-linux-gnu.tar.gz"
[[Xorg_libXcomposite]]
arch = "aarch64"
git-tree-sha1 = "0540e3e35f8bff7620392c925755ca0d99530d3f"
libc = "musl"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "8fc8c322327572ffb720a1c31e5714dc330ce00fa0e7343495513160d884101e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.aarch64-linux-musl.tar.gz"
[[Xorg_libXcomposite]]
arch = "aarch64"
git-tree-sha1 = "ba78e1ff28a716db799b1cc998af2ed7d163c25b"
os = "freebsd"

    [[Xorg_libXcomposite.download]]
    sha256 = "851f12bc978f875e7f3a0e1da0f2e1b5f0fbd6a36d57c8b258185efebb781d49"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXcomposite]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f0926d0b00eb947447a112ecd94a17318fcf4766"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "940962a27fd5054c08b3f6d8988d667ca5b7d40792eb785ebc732b7fe7e981ac"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXcomposite]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b1e09824f8a9421cb4af9b61302e78994fe7887"
libc = "musl"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "db5b5798b44abbd231044daa368d65b47687dd4a663327a01c241dea52fd446d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXcomposite]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1bb65403513ba040e434e252230d2d5cad6d0826"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "66e4773a2f94992932c74b517fee883585c8129921f04e2b9b3419ea8ec35a41"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXcomposite]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9b8f2b4cd2273d8ffec3c65ddcf760ba04bd901d"
libc = "musl"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "14f7e2792bd10b388b054feb89da5df3151c2951fe670795b3b323406561fb28"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXcomposite]]
arch = "i686"
git-tree-sha1 = "14cc4dd44c4f36730ff16f640411a04edf4132de"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "76869a6dffad15373d5d53ad3fbf44de53ab583acef370858ea245dc94251ab6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.i686-linux-gnu.tar.gz"
[[Xorg_libXcomposite]]
arch = "i686"
git-tree-sha1 = "487cacadb429c85db25f4a5ebf688362254d21f2"
libc = "musl"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "9d9cde052a2454be1467d0e165f6c7e9257e45c69a4f0748a4b69ff0bae0a9ed"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.i686-linux-musl.tar.gz"
[[Xorg_libXcomposite]]
arch = "powerpc64le"
git-tree-sha1 = "d090c5c91b8d24695d1b4e8d4222a8c07c127a6c"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "773c59158cfe067a07ecf08970e2c45adc178741f2796e26d872e83fee86a3e6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXcomposite]]
arch = "riscv64"
git-tree-sha1 = "1d7a4895adea297f1ebec68a7e401a0a842468c7"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "1e8b49e97390b07bb9cfe0131afd8b6a39e81066527c406687d1eb6aa7b83fc5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.riscv64-linux-gnu.tar.gz"
[[Xorg_libXcomposite]]
arch = "x86_64"
git-tree-sha1 = "748b3bd189f017e34e952ad928de35f789b04484"
libc = "glibc"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "6ac0db8bbc69edd6f0ffcf5c80af5f68cd0dc3fce29ea1fc0c2e95dfe438c16b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.x86_64-linux-gnu.tar.gz"
[[Xorg_libXcomposite]]
arch = "x86_64"
git-tree-sha1 = "b4457a9f6eff4a6969bb11e0fa53f6088d4c5df3"
libc = "musl"
os = "linux"

    [[Xorg_libXcomposite.download]]
    sha256 = "3b325441caaddd235cc6d1c82e69aeacdb842faf7010a8ec8facbcc09796df5c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.x86_64-linux-musl.tar.gz"
[[Xorg_libXcomposite]]
arch = "x86_64"
git-tree-sha1 = "c821277ee5da8eaea5e12b1f9356601ea4c34372"
os = "freebsd"

    [[Xorg_libXcomposite.download]]
    sha256 = "422a10c2035a961adf6b5f0c52842bee382e700d644d0575c2edca747dc72d0a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcomposite_jll.jl/releases/download/Xorg_libXcomposite-v0.4.7+0/Xorg_libXcomposite.v0.4.7.x86_64-unknown-freebsd.tar.gz"
